#pragma once

#define SEND_BUFF_SIZE			20000
#define RECV_BUFF_SIZE			20000

#define AUTH_SESSION_GROUP			1000

//#define MULTI_ECHO_SESSION_GROUP
#define ECHO_SESSION_GROUP_0		2000
#if defined(MULTI_ECHO_SESSION_GROUP)
#define ECHO_SESSION_GROUP_1		2001
#define ECHO_SESSION_GROUP_2		2002
#define ECHO_SESSION_GROUP_3		2003
#endif

#define AUTH_GROUP_TLSMEMPOOL_UNIT_CNT		1000
#define AUTH_GROUP_TLSMEMPOOL_CAPACITY		1000
#define ECHO_GROUP_TLSMEMPOOL_UNIT_CNT		5000
#define ECHO_GROUP_TLSMEMPOOL_CAPACITY		5000

#define IOCP_WORKER_THREAD_CNT				4
#define CLIENT_CONNECT_LIMIT				20000